#!/bin/bash

for PAIR in $(\
  gcloud compute instances list \
  --project=${PROJECT} \
  --format="csv[no-heading](name,zone.scope(zones))")
do
  # Parse result from above into instance and zone vars
  IFS=, read INSTANCE ZONE <<< ${PAIR}
  # Get the machine type value only
  MACHINE_TYPE=$(\
    gcloud compute instances describe ${INSTANCE} \
    --project=${PROJECT} \
    --zone=${ZONE} \
    --format="value(machineType.scope(machineTypes))")
  # If it's custom-${vCPUs}-${RAM} we've sufficient info
  if [[ ${MACHINE_TYPE}} == custom* ]]
  then
    IFS=- read CUSTOM CPU MEM <<< ${MACHINE_TYPE}
    printf "%s: vCPUs: %s; Mem: %s\n" ${INSTANCE} ${CPU} ${MEM}
  else
    # Otherwise, we need to call `machine-types describe`
    CPU_MEMORY=$(\
      gcloud compute machine-types describe ${MACHINE_TYPE} \
      --project=${PROJECT} \
      --zone=${ZONE} \
      --format="csv[no-heading](guestCpus,memoryMb)")
    IFS=, read CPU MEM <<< ${CPU_MEMORY}
    #printf "%s: vCPUs: %s; Mem: %s\n" ${INSTANCE} ${CPU} ${MEM} >> report.txt
    printf "%s vCPUs %s Mem %s\n" ${INSTANCE} ${CPU} ${MEM}
    printf "%s vCPUs %s Mem %s\n" ${INSTANCE} ${CPU} ${MEM} >> report.txt
    #echo "%s: vCPUs: %s; Mem: %s\n" ${INSTANCE} ${CPU} ${MEM} > report.txt
  fi
done
